name: HypoCycloidPlugin
main: io.github.Gamerick1029.DrawHypoCycloid
version: 1.0
commands:
  drawhc:
    description: "Draws a HypoCycloid made with the /makehc command"
    usage: "Usage: /drawhc [NameOfHC]"
  makehc:
    description: "Creates a new named HypoCycloid"
    usage: "Usage: /makehc [Name of HC] [Ratio of Circles] [Start Cycle] [End Cycle] [Screen Size]" 
  clearhc:
    description: 
    usage: "Usage: /clearhc [Name of HC]"